title: Bilal Ismail
email: bilalahmedismail@yahoo.com
description: >-
ICT Engineer with experience across Networking and Cybersecurity whilst aspiring to adapt towards Informatics (AI) for mobility infrastructure (including robotics).
baseurl: ""
url: ""
markdown: kramdown
plugins: []

