title: Bilal Ismail
email: bilalahmedismail@yahoo.com
description: >-
ICT Engineer with experience across Networking, Cybersecurity, AI, and Robotics.
baseurl: ""
url: ""
markdown: kramdown
plugins: []
